### ISSUE TITLE
 Extending from ClassMethods not possible

### ISSUE THREAD

**Issue by mano87** [zendframework/zend-hydrator#100]
Unfortunately, after updating from zend-hydrator to version 3, our existing classes are no longer functional.

In the methods hydrate () and extract () the strict type "object" throws an error.

Apparently, it is not thought that these classes will be extended. How should we implement this and change our application?

```php
class UserDbHydrator extends ClassMethodsHydrator implements HydratorInterface
{
    protected $colPrefix = 'user_';
    protected $colIgnoreList = ['username', 'password'];

    public function hydrate(array $data, object $object)
    {
        $array = $this->removePrefix($data, $this->colPrefix);
        $hydrated_array = parent::hydrate($array, $object);
        return $hydrated_array;
    }

    public function extract(object $object): array
    {
        $extracted_array = parent::extract($object);
        $array = $this->appendPrefix($extracted_array, $this->colPrefix, $this->colIgnoreList);
        return $array;
    }

    public function appendPrefix($array, $prefix, $ignore)
    {
        $data = [];
        foreach ($array as $key => $value) {
            if ((!preg_match('/^' . $prefix . '/', $key)) and (!in_array($key, $ignore))) {
                $key = $prefix . $key;
            }
            $data[$key] = $value;
        }
        return $data;
    }

    public function removePrefix($array, $prefix)
    {
        $data = [];
        foreach ($array as $key => $value) {
            if (preg_match('/^' . $prefix . '/', $key)) {
                $key = preg_replace('/^' . $prefix . '/', '', $key);
            }
            $data[$key] = $value;
        }
        return $data;
    }
}
```

**Comment by froschdesign** [comment]
@mano87 
> In the methods hydrate () and extract () the strict type "object" throws an error.

What error?

> Apparently, it is not thought that these classes will be extended.

Not right.

**Comment by weierophinney** [comment]
I see nothing wrong with the signatures above, and without an example error message, it's impossible for us to try and debug.

The only difference that having strict types enabled and providing type hints makes is that if you are providing bad arguments or returning invalid values, you will get PHP errors. If that's the case, then you need to check your code, as it was technically invalid prior to the update, and needs to be fixed.

Please provide us some examples of the errors you receive so we can help you better. Thanks!

**Comment by mano87** [comment]
@weierophinney 

Here is a screenshot from PhpStorm. Unfortunately, we rolled back our application back to the zend-hydrator 2. As soon as I have time, I post the mistakes we received after the changeover.

https://imgur.com/a/wfwxXnb

**Comment by froschdesign** [comment]
@mano87 
Which PHP version do you use and which version is configured in PhpStorm? (You need PHP 7.2 or higher for version 3 of zend-hydrator.)

**Comment by mano87** [comment]
@froschdesign 
We use version 7.2.14, locally and in PhpStorm. Already at the override of the hydrate method we get this error.

**Comment by froschdesign** [comment]
@mano87 
Please recheck which version is configured in PhpStorm under `Preferences | Languages and Frameworks | PHP`. Your screenshot shows a problem which belongs to an older PHP version than 7.2.

See:
* https://www.jetbrains.com/help/phpstorm/php.html
* http://php.net/manual/en/migration72.new-features.php#migration72.new-features.object-type

**Comment by Ocramius** [comment]
Closing here meanwhile: without a test case, this isn't going anywhere.

Besides that:

 > Apparently, it is not thought that these classes will be extended. 

Composition over inheritance, if possible ;-)

**Comment by RalfEggert** [comment]
But shouldn't these classes or methods then be have the final attribution if they are not intended to be extended? Just being curious here.

**Comment by froschdesign** [comment]
@RalfEggert 
> …if they are not intended to be extended?

"Composition over inheritance" does not automatically mean that it is no longer possible to extend it.

**Comment by mano87** [comment]
@froschdesign 
https://imgur.com/a/dcbYGl6

**Comment by froschdesign** [comment]
@mano87 
I have the same settings in PhpStorm without any problems. It is a problem / wrong setting in your PhpStorm because [PHP allows the object type](http://php.net/manual/en/migration72.new-features.php#migration72.new-features.object-type) and [all builds on Travis are also green](https://travis-ci.org/zendframework/zend-hydrator).
Have you ever run your script?

--- 
Btw. You can add your images here on GitHub in your comment. 😃

**Comment by Ocramius** [comment]
Yes, composition over inheritance is not enforced, but helping in building a foot-gun is also not something I'd do, and surely not for free 😜

That said, issue was closed due to lacking tests, not because of my opinion about architecture.
