### ISSUE TITLE
CamelCaseToUnderscoreFilter

### ISSUE THREAD

**Issue by boesing** [zendframework/zend-hydrator#102]
Hey there,

I've created #101 with a failing unit test.
The `CamelCaseToUnderscoreFilter` filters the name totally different than the old one:

**zend-filter + strtolower (as in zend-hydrator v2)**
```
bfd7b82e9cfceaa82704d1c1_foo
```

**CamelCaseToUnderscoreFilter (as in zend-hydrator v3)**
```
bfd_7_b82e_9_cfceaa_82704_d1c_1_foo
```

**Comment by samsonasik** [comment]
should be closeable now

**Comment by Ocramius** [comment]
Thanks @samsonasik @boesing!
