### ISSUE TITLE
possible BC break

### ISSUE THREAD

**Issue by svycka** [zendframework/zend-hydrator#19]
after ZF2.5.3 release many components got updated and hydrator also:

```
...
  - Removing zendframework/zend-stdlib (2.5.2)
  - Installing zendframework/zend-stdlib (2.7.4)
    Downloading: 100%         

  - Installing zendframework/zend-hydrator (1.0.0)
    Downloading: 100%         
...
```
after update throws this exception

> PHP Catchable fatal error:  Argument 1 passed to FarmActivity\\Hydrator\\Factory\\ActivityHydratorFactory::FarmActivity\\Hydrator\\Factory\\{closure}() must be an instance of Zend\\Stdlib\\Hydrator\\Aggregate\\ExtractEvent, instance of Zend\\Hydrator\\Aggregate\\ExtractEvent given in /var/www/farmmanager/module/FarmActivity/src/FarmActivity/Hydrator/Factory/ActivityHydratorFactory.php on line 34

I see that `Zend\Stdlib\Hydrator\Aggregate\AggregateHydrator` is deprecated so I assume someone missed something with backwards compatibility :-)

**Comment by svycka** [comment]
just quick replace `Zend\Stdlib\Hydrator` to `Zend\Hydrator` fixed everything so this is definitely BC break

**Comment by svycka** [comment]
Problem is when creating event https://github.com/zendframework/zend-hydrator/blob/master/src/Aggregate/AggregateHydrator.php#L45 and https://github.com/zendframework/zend-hydrator/blob/master/src/Aggregate/AggregateHydrator.php#L57,  but closure expects `Zend\Stdlib\Hydrator\Aggregate\ExtractEvent` so I think these two methods should be copied to stdlib and changed to correct event class. I could create a PR for stdlib but don't know the branch on with I could create one since stdlib master is 3.0 :-)

I haven't tested this but it looks like this could work.

**Comment by weierophinney** [comment]
@svycka PRs for that can be done against the release-2.7 branch of zend-stdlib. I'm going to try and work something up now.

**Comment by weierophinney** [comment]
Closing as the fix needs to be done on zend-stdlib, and zendframework/zend-stdlib#55 reports it there.
