### ISSUE TITLE
zend-hydrator requires package zend-servicemanager

### ISSUE THREAD

**Issue by Danack** [zendframework/zend-hydrator#29]
The dependency on zend-servicemanager is listed under 'dev dependencies' in the [composer file](https://github.com/zendframework/zend-hydrator/blob/master/composer.json#L23).

However the HydratorPluginManager class [extends a class](https://github.com/zendframework/zend-hydrator/blob/master/src/HydratorPluginManager.php#L21) from that package, and so gives the error:

> Class 'Zend\ServiceManager\AbstractPluginManager' not found

If you attempt to use it without also having the service manager installed.

**Comment by Danack** [comment]
hmm - apparently the docs at http://framework.zend.com/manual/current/en/modules/zend.stdlib.hydrator.html need updating also.

Doing `new Zend\Hydrator\HydratorPluginManager` now gives an error:

> Zend\ServiceManager\AbstractPluginManager::__construct now expects a Interop\Container\ContainerInterface instance representing the parent container; please update your code

**Comment by samsonasik** [comment]
the doc you pointed is for zf 2.4 which not using zend-hydrator ( use `zend\stdlib\hydrator` ) instead.
