### ISSUE TITLE
ClassMethods throws exception on missing setter when hydrate object

### ISSUE THREAD

**Issue by hrasekj** [zendframework/zend-hydrator#50]
Hello,

I'm not sure if its bug or feature. In method [ClassMethods::hydrate](https://github.com/zendframework/zend-hydrator/blob/master/src/ClassMethods.php#L208) is used php function `is_callable` to determine if setter is callable or not. But this function only checks syntax and does not check if setter really exists or is public. In this case function `is_callable` always returns true.

So instead of `is_callable` there should be `method_exists`, but there is a catch. Function `method_exists` only checks if method really exists, but doesn't care if is public.

I think there should be this condition:
```php
(new \ReflectionClass($object))->hasMethod($setterName) && (new \ReflectionMethod($object, $setterName))->isPublic()
```

In tests should be this:
```php
        $classMethodsCamelCase = $this->hydrator->hydrate(
            ['fooBarBaz' => 'baz-tab'],
            new ClassMethodsCamelCase()
        );
        $classMethodsCamelCaseMissing = $this->hydrator->hydrate(
            ['fooBarBaz' => 'baz-tab'],
            new ClassMethodsCamelCaseMissing()
        );

        $this->assertSame('baz-tab', $classMethodsCamelCase->getFooBarBaz());
        $this->assertSame('2', $classMethodsCamelCaseMissing->getFooBarBaz());
```

**Comment by froschdesign** [comment]
> But this function only checks syntax…

…if the second parameter set to `true`.

http://php.net/manual/en/function.is-callable.php

**Comment by hrasekj** [comment]
Yeah, you are right. The problem here was in magic method `__call`. When its present in object is_callable returns true every time.

**Comment by froschdesign** [comment]
@hrasekj 
Thanks for your feedback!

> Yeah, you are right. The problem here was in magic method __call. When its present in object is_callable returns true every time.

Please have a look at this proposal: #44 - "ClassMethods: Add switch to prevent the call of __call as setter"
