### ISSUE TITLE
Unexpected behaviour when hydrating objects from Form inputs and from Database

### ISSUE THREAD

**Issue by ddodz** [zendframework/zend-hydrator#61]
If we use strategies attached to hydrator to do hydration, a method is called `AbstractHydrator::hydrateValue($name, $value, $data = null)`. If we attach a strategy to hydrator using `addStrategy()` method, for hydration to take place, a `$name` must 100% match a key in the `$data` array. Here is the problem. Usually in the forms, people give names to `<input>`s with first letter lower-case, like `someName`. In databases, the column names are usually with the first letter capital, like `SomeName`. Then the name of the strategy you attach via `addStrategy()` starts to depend on where you get the `$data` array from: if from database, you must name strategy as `SomeName` (first letter capital), if from form, you must name the strategy `someName` (first letter lower-case) for object hydration to succeed. The two together cannot live.

This's quite annoying. Perhaps someone could fix it.

**Comment by froschdesign** [comment]
@ddodz 
> Usually in the forms, people give names to <input>s with first letter lower-case, like someName. In databases, the column names are usually with the first letter capital, like SomeName.

Usually – maybe in your use case.

> The two together cannot live.

The [`CompositeNamingStrategy`](https://docs.zendframework.com/zend-hydrator/naming-strategy/composite-naming-strategy/) could help.

**Comment by ddodz** [comment]
> Usually – maybe in your use case.

There is subjectivity in naming, I agree. The "best practices", if you can call them like these, are from a DB designer and webdeveloper as I wrote. 

> The CompositeNamingStrategy could help.

Not sure this will help. Depending on where the call for hydration comes from, either from form (to save in DB) or from a db mapper (to show data on the webpage), you'll have to use either first-letter-lower-case strategy or first-letter-capitalized strategy respectively. So you need a mechanism of distinguishing where the hydration call comes from and attach the `CompositeNamingStrategy` based on that. I don't see an easy way of implementing this.

**Comment by froschdesign** [comment]
@ddodz 
> So you need a mechanism of distinguishing where the hydration call comes from…

Add or remove a naming strategy. Example:

```php
$hydrator = new \Zend\Hydrator\ClassMethods(false);

$hydrator->hydrate(
    [
        'SomeName' => 'Foo',
    ],
    $foo
);
var_dump($hydrator->extract($foo));
// array (size=1) 'someName' => string 'Foo' (length=3)

$hydrator->setNamingStrategy(
    new Zend\Hydrator\NamingStrategy\MapNamingStrategy(
        [
            'SomeName' => 'someName',
        ]
    )
);

$hydrator->hydrate(
    [
        'someName' => 'Bar',
    ],
    $foo
);
var_dump($hydrator->extract($foo));
// array (size=1) 'SomeName' => string 'Bar'
```
Is this behaviour correct?

**Comment by ddodz** [comment]
@froschdesign thanks, my friend. What you write is correct, but the problem is elsewhere. Let's assume hydration is done using a strategy. You attach the strategy to the hydrator via `addStrategy()`. 

Look at the code of `AbstractHydrator::hydrateValue($name, $value, $data = null)`. You'll see that for hydration to succeed, strategy name (`$name`) must == a key in array `$data`. The `$data` array is either array of html input names or array of DB column names. Now, if you hydrate in form, you have to ensure that the html input name == strategy name. If you hydrate in mapper, DB column name must == strategy name. For hydration to work well for both form and mapper, html input name should == column name. But if DB column name != strategy name (strategy name is `someName` and column name is `SomeName`) and html input name == strategy name, the errors appear when you hydrate using mapper. You could compensate for difference between column name and strategy name, as you suggested, using `MapNamingStrategy()`. But in this case, you must know upfront where the hydration takes place (in form or in mapper) so that you can prepare the hydrator accordingly. This means that you have to have either two separate hydrators and inject either of them based on where you hydrate, or use a hydrator factory that modifies the behaviour based on where hydration takes place (form or mapper). I don't think things should work like this, I believe this needs to be corrected in the source code of ZF3.

This whole explanation is a little cryptic, but I hope you understand what I mean.

**Comment by froschdesign** [comment]
> I think the source code of ZF3 should be corrected.

Unfortunately, there is a misunderstanding. The source code is correct! Nothing is wrong. zend-hydrator works like [documented](https://docs.zendframework.com/zend-hydrator/). See also the blog post from today: "[framework.zend.com - Convert objects to arrays and back with zend-hydrator](https://framework.zend.com/blog/2017-06-21-zend-hydrator.html)"

You want a different behavior, which is not covered by the current implementation.

**Comment by ddodz** [comment]
I understand, Frank. I wasn't saying the source code was wrong. The current implementation has a drawback though. It makes the strategy name dependent on both DB column names and html input names (I mean lower-case first letter and upper-case first letter thing). If there is a mismatch between those, you're running into problems. In the end, I spent 3 hours on trying to figure out what the problem was, and I may not be the only one who spent time on this :-)

**Comment by weierophinney** [comment]
I've reviewed this exchange, and I agree with @froschdesign 

You need to hydrate _for the context in which you will be consuming the end product_. If that means the end produce needs the key names to be StudlyCaps, you will need to ensure your hydrator is configured accordingly. If you then need a different set of rules for extracting data for purposes of generating a JSON payload, you will need to create a different hydrator for that purpose.

While the general use case is for hydrators to be bi-directional, complicated use cases such as those you outlined require either asymmetric extraction/hydration strategies, **or** you need to create something custom. The latter can be done by implementing `ExtractionInterface`, `HydrationInterface`, or `HydratorInterface` (which is a union of the previous two). These can be created as anonymous classes, by extending or composing the shipped versions, or as dedicated classes you write yourself. Typically, however, I would not rely on strategies and naming strategies _unless you are using the shipped hydrators without changes_; those features exist to customize those specific approaches to allow them to act as general purpose hydrators. If you need something specific... the general-purpose hydrators are not the solution.
