### ISSUE TITLE
Mili/microseconds problem with DateTimeFormatterStrategy

### ISSUE THREAD

**Issue by vaclavvanik** [zendframework/zend-hydrator#71]
I use postgres with `datetime with timezone` columns. Possible value types are:

```
$dates = [
    '2016-03-04 10:29:40+01',
    '2016-03-04 10:29:40.123456+01',
];
```

I think there is no way to create [parse format](http://php.net/manual/en/datetime.createfromformat.php) with optional part - in this example miliseconds. 

Imo this can be solved with little DateTimeFormatterStrategy hydrate modification:

```
    public function hydrate($value)
    {
        if ($value === '' || $value === null) {
            return;
        }

        if ($this->timezone) {
            $hydrated = DateTime::createFromFormat($this->format, $value, $this->timezone);
        } else {
            $hydrated = DateTime::createFromFormat($this->format, $value);
        }

        if (false === $hydrated) {
            // this is fallback when createFromFormat does not work
            $hydrated = new DateTime($value, $this->timezone);
        }

        return $hydrated ?: $value;
    }
```

Thoughts?

**Comment by vaclavvanik** [comment]
Could someone confirm that current behaviour is not happy?

Ping @weierophinney @froschdesign

**Comment by froschdesign** [comment]
@vaclavvanik 
Sorry for the very late response. zend-hydrator was under my radar.

The fallback should be optional, otherwise it would be a BC break.

**Comment by froschdesign** [comment]
@vaclavvanik 
Can you create a PR with unit tests? That would be great!

---

Btw. At the moment the strategy is limited to the `DateTime` class, but `DateTimeImmutable` is also important.

**Comment by vaclavvanik** [comment]
@froschdesign [PR](https://github.com/zendframework/zend-hydrator/pull/79) created
