### ISSUE TITLE
undeclared dependency on zend-servicemanager

### ISSUE THREAD

**Issue by achevo01** [zendframework/zend-hydrator#72]
This package has a dependency on  zend-servicemanager but this dependency is not declared in the composer.json.

An example of this would be the `Zend\ServiceManager\FactoryInterface` in the HydratorPluginManagerFactory.php file.

I would suggest updating the composer.json file to include zend-servicemanager as a dependency.

**Comment by Ocramius** [comment]
Related: https://github.com/zendframework/zend-hydrator/issues/29

@achevo01 including the dependency is feasible, but was avoided upfront due to too many library inter-dependencies. I'd suggest polyfilling instead of adding another dependency.

**Comment by froschdesign** [comment]
zend-servicemanager is not strictly required for this component and therefore it is included in the suggest section of the Composer file:

https://github.com/zendframework/zend-hydrator/blob/c16f3d471c2bbef0568ce9ae1fef892321237ee8/composer.json#L28-L33

So it would be an improvement if the dependency can be removed.

**Comment by Ocramius** [comment]
Handled in #87
