### ISSUE TITLE
allow string name as HydrationInterface::hydrate() second parameter

### ISSUE THREAD

**Issue by marcosh** [zendframework/zend-hydrator#8]
The docblock above the definition of `hydrate` in the `HydrationInterface` says that the second parameter should be an object.

This implies that the second argument must be an object already costructed, that we are going to mutate to make it hydrated.

I would like to use the hydrator to construct a new object so that I can pass the array values directly to the constructor of my object, in such a way that the object is created already in a valid state and there is no need of mutation to hydate it completely.

This would be possible just allowing the second parameter to be a class name, and not a class instance.

I understand that this would make the hydrator also a factory, but in my opinion the benefits exceed this drawback.

What do you think?

**Comment by Ocramius** [comment]
I think this goes against the idea of the hydrator itself. What you are
trying to build is a serializer, which is much more complicated ;-)

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by marcosh** [comment]
@Ocramius I'm looking at what you wrote [here](https://github.com/zendframework/zf2/issues/5051#issuecomment-23598562). From that pipeline it doesn't seem to me that I am looking for a serializer. It would fit much more nicely as an hydrator or as a data-transformer (but in this case, if I have alredy my object completely constructed, I don't see why I would need an hydrator later on).

The other option to do what I'd like to seems to me to use an intermediate object that will be hydrated. Then I could use the intermediate object to build the object I'm really interesetd in

**Comment by Maks3w** [comment]
I'm agree with @ocramius. For me the meaning of hydrator has been always add data to an existing object. 

Now I start to think if hydrators still been so relevant with immutable patterns. 

Obviously hydrators are still useful for mutable entities. 

Should we implement something with immutable objects (constructor arguments) in mind?

**Comment by marcosh** [comment]
@Maks3w I think it sounds like a nice thing to have. In the pipeline proposed by @Ocramius that I referenced in my previous comment, I think that such a component (something like an abstract factory that builds objects from input data) could come right before the hydrator

**Comment by Ocramius** [comment]
Right, but that is not what this issue proposes.

I will close here, as this is indeed the wrong approach to the problem: consider re-opening after re-speccing (and maybe looking at the original suggestion again, or continuing there)

**Comment by alefcastelo** [comment]
@Ocramius 

I think it would be good something like $hydrator->hydrate($data, ClassName::class)

https://gist.github.com/alefcastelo/3f16b9213c0b05080f302543f046ffe5
https://gist.github.com/alefcastelo/e5e9b55d2843940e3d3f654cdfda3001
https://gist.github.com/alefcastelo/7769d29a351dea3b762eb1a64c84593d

**Comment by froschdesign** [comment]
@alefcastelo 
I think, it is usefull to create a new issue report with your suggestion.
