### ISSUE TITLE
This part break apigility admin 

### ISSUE THREAD

**Issue by newdevonair** [zendframework/zend-hydrator#95]
https://github.com/zendframework/zend-hydrator/blob/83568db2beb6a529e55f821f589ffea9ac8dc140/src/Filter/FilterComposite.php#L124
when create a new field on REST service or try to open REST service php throw exception.
the reason is argument for filter(string $value)  is integer.
```
'input_filter_specs' => [
    "POST" => [
        0 => [ // Argument 1 passed to Zend\Hydrator\Filter\FilterComposite::filter() must be of the type string, integer given
            'required' => true,
            'validators' => [],
            'filters' => [],  
            'name' => 'test_filed', 
        ],
    ],
],
```
@weierophinney  can you please review this changes,
it`s done by this commit https://github.com/zendframework/zend-hydrator/commit/7b6d85e1dab219499b4431a598b1065684bcfd95#diff-164cac30a1f18281587e41a02a3ee036

**Comment by froschdesign** [comment]
@newdevonair 
Sorry, but this is the wrong issue tracker for this problem.

The `input_filter_specs` is for [zend-inputfilter](https://docs.zendframework.com/zend-inputfilter/) and has nothing to do with [zend-hydrator](https://docs.zendframework.com/zend-hydrator/).
Try to find the correct position of the problem in the code and then report this on [zfcampus/zf-apigility-admin](https://github.com/zfcampus/zf-apigility-admin/issues).
