### ISSUE TITLE
No issue, just a silly question...

### ISSUE THREAD

**Issue by pine3ree** [zendframework/zend-hydrator#99]
..to be closed at once...

I've always wondered about the HydrationInterface method signature;

`public function hydrate(array $data, object $object)`

Why doeasn't the direct object come first?
`public function hydrate(object $object, array $data)` 

hydrate($theTargetOfTheAction, $withThisData)

The naming strategy hydrator use the target / direct object aka the $name as first argument

sorry for asking, kind regards

**Comment by weierophinney** [comment]
Honestly, I cannot remember the rationale when we first added these. At this point, changing it would be a massive BC break, so :man_shrugging: .

**Comment by pine3ree** [comment]
> At this point, changing it would be a massive BC break, so  .

I know....just curious, I guess I will keep on decorating them....:-)  thanks!!!

**Comment by Xerkus** [comment]
Object could be optional, with prototype object already set in hydrator. And php requires optional arguments to be at the end.
Pretty sure that was the rationale back at the time.

**Comment by pine3ree** [comment]
Hello @Xerkus, 
...but the HydrationInterface method signature requires it, it is not optional (maybe it was in earlier versions?)
```php
public function hydrate(array $data, object $object);
```
kind regards

**Comment by Xerkus** [comment]
Implementors/extending classes can declare parameters optional, granted they are after all the required. Obviously, you can no longer rely on interface when skipping such optional parameters.

As for the prototype and optional $object in hydrators, I do not see it in codebase. Looks like it didn't make out of early development, immediately obsoleted by better approach:
https://github.com/zendframework/zend-db/blob/77022f06f6ffd384fa86d22ab8d8bbdb925a1e8e/src/ResultSet/HydratingResultSet.php#L107

**Comment by pine3ree** [comment]
@Xerkus 
yep, php interfaces are a little permissive about that.
I checked the first version https://github.com/zendframework/zend-stdlib/blob/release-2.0.0/src/Hydrator/HydratorInterface.php#L35 still not optional in the signature. But I now understand that one could think about having a default hydrator carrying prototype, thus the order of the ctor args.
(....I am still decorating them anyway :-P)
Thanks for the info....
kind regards.
